spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/project_db
    username: root
    password: dbit
    driver-class-name: org.mariadb.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB     # 개별 파일(또는 폼 필드)의 최대 허용 크기
      max-request-size: 50MB   # 전체 요청(파일 + 나머지)의 최대 허용 크기
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mybatis:
    configuration:
      map-underscore-to-camel-case: true
server:
  tomcat:
    max-http-post-size: 52428800